import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { WorkbenchItem } from '../stores/workbenchStore';
import type { ReportSelection } from '../components/workbench/WorkbenchReportModal';
import { getEvidenceChartsForInsight } from './insightEvidenceData';
import { getAllKPIInsights } from './kpiInsights';

// PDF Configuration
const CONFIG = {
  colors: {
    primary: '#14B8A6', // Teal
    text: '#333333',
    lightText: '#666666',
    border: '#E5E7EB',
    background: '#F9FAFB',
  },
  margins: {
    left: 20,
    right: 20,
    top: 30,
    bottom: 25,
  },
  fontSize: {
    title: 24,
    heading1: 18,
    heading2: 14,
    heading3: 12,
    body: 10,
    small: 8,
  },
  pageWidth: 210, // A4 width in mm
  pageHeight: 297, // A4 height in mm
};

/**
 * Capture chart as image using html2canvas
 */
const captureChart = async (chartId: string): Promise<string | null> => {
  try {
    const chartElement = document.getElementById(chartId);

    if (!chartElement) {
      console.warn(`Chart element not found: ${chartId}`);
      return null;
    }

    const canvas = await html2canvas(chartElement, {
      scale: 2,
      backgroundColor: '#ffffff',
      logging: false,
      useCORS: true,
      allowTaint: true,
    });

    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error(`Error capturing chart ${chartId}:`, error);
    return null;
  }
};

/**
 * Add page header with page number
 */
const addPageHeader = (doc: jsPDF, pageNumber: number): void => {
  doc.setFontSize(CONFIG.fontSize.small);
  doc.setTextColor(CONFIG.colors.lightText);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Page ${pageNumber}`,
    CONFIG.pageWidth - CONFIG.margins.right,
    CONFIG.margins.top - 10,
    { align: 'right' }
  );
};

/**
 * Check if we need a new page and add one if necessary
 */
const checkAddNewPage = (doc: jsPDF, yPosition: number, requiredSpace: number = 40): number => {
  if (yPosition + requiredSpace > CONFIG.pageHeight - CONFIG.margins.bottom) {
    doc.addPage();
    return CONFIG.margins.top;
  }
  return yPosition;
};

/**
 * Generate collated workbench report with selected insights and evidence
 */
export const generateCollatedWorkbenchReport = async (
  selections: ReportSelection,
  workbenchItems: WorkbenchItem[],
  onProgress?: (progress: number, message: string) => void
): Promise<void> => {
  try {
    onProgress?.(0, 'Initializing PDF generation...');

    // Initialize PDF
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    let currentY = CONFIG.margins.top;
    let pageNumber = 1;

    // ========== COVER PAGE ==========
    onProgress?.(5, 'Creating cover page...');

    // Title
    doc.setFontSize(CONFIG.fontSize.title + 4);
    doc.setTextColor(CONFIG.colors.primary);
    doc.setFont('helvetica', 'bold');
    doc.text('Workbench Report', CONFIG.pageWidth / 2, 80, { align: 'center' });

    // Date
    const reportDate = new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });
    doc.setFontSize(CONFIG.fontSize.heading2);
    doc.setTextColor(CONFIG.colors.text);
    doc.setFont('helvetica', 'normal');
    doc.text(reportDate, CONFIG.pageWidth / 2, 95, { align: 'center' });

    // Horizontal line
    doc.setDrawColor(CONFIG.colors.primary);
    doc.setLineWidth(1);
    doc.line(40, 105, CONFIG.pageWidth - 40, 105);

    // Summary box
    const selectedInsights = Object.entries(selections).filter(([_, sel]) => sel.insightSelected);
    const totalEvidence = Object.values(selections).reduce(
      (sum, sel) => sum + Object.values(sel.evidenceCharts).filter(Boolean).length,
      0
    );

    doc.setFillColor(CONFIG.colors.background);
    doc.roundedRect(40, 120, CONFIG.pageWidth - 80, 60, 3, 3, 'F');

    doc.setFontSize(CONFIG.fontSize.body);
    doc.setTextColor(CONFIG.colors.text);
    let summaryY = 132;
    doc.text(`Total Insights: ${selectedInsights.length}`, 50, summaryY);
    summaryY += 8;
    doc.text(`Total Evidence Charts: ${totalEvidence}`, 50, summaryY);
    summaryY += 8;
    doc.text(`Generated: ${new Date().toLocaleString('en-US')}`, 50, summaryY);
    summaryY += 8;
    doc.text(`Generated by: CR360 Agent Hub`, 50, summaryY);

    // Add first content page
    doc.addPage();
    pageNumber++;
    addPageHeader(doc, pageNumber);
    currentY = CONFIG.margins.top + 10;

    // ========== INSIGHTS AND EVIDENCE ==========
    const totalSteps = selectedInsights.length;
    let currentStep = 0;

    for (const [insightId, selection] of Object.entries(selections)) {
      if (!selection.insightSelected) continue;

      currentStep++;
      const progress = 10 + Math.floor((currentStep / totalSteps) * 80);

      // Find the workbench item
      const workbenchItem = workbenchItems.find(item => item.insightId === insightId);
      if (!workbenchItem) continue;

      // Find the full insight details
      const allInsights = getAllKPIInsights();
      const fullInsight = allInsights.find(i => i.id === insightId);

      onProgress?.(progress, `Processing: ${workbenchItem.title}`);

      // Check if we need a new page for this insight
      currentY = checkAddNewPage(doc, currentY, 60);

      // Insight Title
      doc.setFontSize(CONFIG.fontSize.heading1);
      doc.setTextColor(CONFIG.colors.primary);
      doc.setFont('helvetica', 'bold');

      // Add severity indicator
      const severityColor =
        workbenchItem.severity === 'critical'
          ? '#EF4444'
          : workbenchItem.severity === 'warning'
          ? '#F97316'
          : '#3B82F6';
      doc.setFillColor(severityColor);
      doc.circle(CONFIG.margins.left + 2, currentY - 2, 2, 'F');

      doc.text(workbenchItem.title, CONFIG.margins.left + 8, currentY);
      currentY += 10;

      // Severity badge
      doc.setFontSize(CONFIG.fontSize.small);
      doc.setTextColor(CONFIG.colors.lightText);
      doc.setFont('helvetica', 'normal');
      doc.text(
        `${workbenchItem.severity.toUpperCase()} SEVERITY`,
        CONFIG.margins.left,
        currentY
      );
      currentY += 8;

      // Implication
      doc.setFontSize(CONFIG.fontSize.body);
      doc.setTextColor(CONFIG.colors.text);
      doc.setFont('helvetica', 'normal');

      const implLines = doc.splitTextToSize(
        workbenchItem.description,
        CONFIG.pageWidth - CONFIG.margins.left - CONFIG.margins.right
      );
      doc.text(implLines, CONFIG.margins.left, currentY);
      currentY += implLines.length * 5 + 5;

      // Key Insights (if available)
      if (fullInsight?.keyInsights && fullInsight.keyInsights.length > 0) {
        currentY = checkAddNewPage(doc, currentY, 30);

        doc.setFontSize(CONFIG.fontSize.heading3);
        doc.setFont('helvetica', 'bold');
        doc.text('Key Insights:', CONFIG.margins.left, currentY);
        currentY += 7;

        doc.setFontSize(CONFIG.fontSize.small);
        doc.setFont('helvetica', 'normal');

        fullInsight.keyInsights.forEach((insight, idx) => {
          currentY = checkAddNewPage(doc, currentY, 10);
          const insightLines = doc.splitTextToSize(
            `${idx + 1}. ${insight}`,
            CONFIG.pageWidth - CONFIG.margins.left - CONFIG.margins.right - 5
          );
          doc.text(insightLines, CONFIG.margins.left + 5, currentY);
          currentY += insightLines.length * 4 + 3;
        });

        currentY += 5;
      }

      // Evidence Charts
      const evidenceCharts = getEvidenceChartsForInsight(insightId);
      const selectedCharts = evidenceCharts.filter(
        chart => selection.evidenceCharts[chart.id]
      );

      if (selectedCharts.length > 0) {
        currentY = checkAddNewPage(doc, currentY, 20);

        doc.setFontSize(CONFIG.fontSize.heading2);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(CONFIG.colors.primary);
        doc.text('Evidence', CONFIG.margins.left, currentY);
        currentY += 10;

        // Render charts
        for (const chart of selectedCharts) {
          currentY = checkAddNewPage(doc, currentY, 90);

          // Chart title
          doc.setFontSize(CONFIG.fontSize.heading3);
          doc.setTextColor(CONFIG.colors.text);
          doc.setFont('helvetica', 'bold');
          doc.text(chart.title, CONFIG.margins.left, currentY);
          currentY += 7;

          // Key highlight
          if (chart.keyHighlight) {
            doc.setFontSize(CONFIG.fontSize.small);
            doc.setFont('helvetica', 'italic');
            doc.setTextColor(CONFIG.colors.lightText);
            const highlightLines = doc.splitTextToSize(
              chart.keyHighlight,
              CONFIG.pageWidth - CONFIG.margins.left - CONFIG.margins.right
            );
            doc.text(highlightLines, CONFIG.margins.left, currentY);
            currentY += highlightLines.length * 4 + 5;
          }

          // Capture and add chart image
          const chartImageData = await captureChart(`hidden-chart-${chart.id}`);

          if (chartImageData) {
            const imgWidth = CONFIG.pageWidth - CONFIG.margins.left - CONFIG.margins.right;
            const imgHeight = 70; // Fixed height for charts

            currentY = checkAddNewPage(doc, currentY, imgHeight + 5);

            doc.addImage(
              chartImageData,
              'PNG',
              CONFIG.margins.left,
              currentY,
              imgWidth,
              imgHeight
            );
            currentY += imgHeight + 10;
          } else {
            doc.setFontSize(CONFIG.fontSize.small);
            doc.setTextColor(CONFIG.colors.lightText);
            doc.text('[Chart could not be rendered]', CONFIG.margins.left, currentY);
            currentY += 10;
          }
        }
      }

      // Add some space before next insight
      currentY += 10;

      // Page break before next insight if we're past halfway
      if (currentY > CONFIG.pageHeight / 2) {
        doc.addPage();
        pageNumber++;
        addPageHeader(doc, pageNumber);
        currentY = CONFIG.margins.top + 10;
      }
    }

    onProgress?.(95, 'Finalizing PDF...');

    // Save the PDF
    const filename = `workbench-report-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);

    onProgress?.(100, 'Report generated successfully!');
  } catch (error) {
    console.error('Error generating collated PDF:', error);
    throw error;
  }
};
